from . import prestashop
from . import stock
from . import product
from . import res_partner
from . import sale
from . import account
from . import message
from . import cart_rules
from . import catalog_price_rules
from . import prestashop_dashboard
from . import sale_shop
from . import import_order_workflow
from . import prestashop_logs 
from . import prestashop_language
from . import presta_schedular
from . import res_lang
from . import res_country
from . import res_country_state
